In [1]:
!pip install ipython-sql
!pip install pyodbc

Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.12.0-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: ipython in c:\users\velve\anaconda3\lib\site-packages (from ipython-sql) (8.27.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\velve\anaconda3\lib\site-packages (from ipython-sql) (2.0.34)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: six in c:\users\velve\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\velve\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\velve\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\velve\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.1)
Requirement already satisfied: decorator in c:\users\velve\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\velve\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in c:\users\velve\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\velve\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\velve\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\velve\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\velve\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\velve\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\velve\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\velve\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\velve\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\velve\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\velve\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading prettytable-3.12.0-py3-none-any.whl (31 kB)
Downloading sqlparse-0.5.3-py3-none-any.whl (44 kB)
Installing collected packages: sqlparse, prettytable, ipython-sql
Successfully installed ipython-sql-0.5.0 prettytable-3.12.0 sqlparse-0.5.3
Requirement already satisfied: pyodbc in c:\users\velve\anaconda3\lib\site-packages (5.1.0)

In [2]:
import pandas as pd
import pyodbc

In [4]:
conn = pyodbc.connect("Driver={SQL Server};Server=localhost\\SQLEXPRESS;Database=cw2;")

In [5]:
conn.close()

In [7]:
conn = pyodbc.connect("Driver={SQL Server};Server=localhost\\SQLEXPRESS;Database=cw2;")

In [8]:
cursor= conn.cursor()

In [11]:
conn.close()

In [12]:
conn = pyodbc.connect("Driver={SQL Server};Server=localhost\\SQLEXPRESS;Database=cw2;")
cursor = conn.cursor()

insert_car_query = """
INSERT INTO car (regnum, make, model, dateofman, mileage, nextsdate)
VALUES (?, ?, ?, ?, ?, ?);
"""
car_values = ['AAA 123', 'Volkswagen', 'Polo', '2024-06-30', 49904, '2024-09-18']

cursor.execute(insert_car_query, car_values)

insert_service_query = """
INSERT INTO service (sid, dropoff_date, dropoff_time, worktext, regnum)
VALUES (?, ?, ?, ?, ?);
"""
service_values = ['S2006-136', '2024-09-12', '14:30:00', 'New service has been booked', 'AAA 123']
cursor.execute(insert_service_query, service_values)

conn.commit()
conn.close()

In [18]:
conn = pyodbc.connect("Driver={SQL Server};Server=localhost\\SQLEXPRESS;Database=cw2;")
cursor = conn.cursor()

###############################
selectQuery = """
SELECT e.empname AS mechanic_name, e.grade AS mechanic_grade, COUNT(w.[sid]) AS number_of_jobs 
FROM work w
JOIN emp e ON w.empid = e.empid
JOIN [service] s1 ON w.[sid] = s1.[sid]
JOIN [service] s2 ON s1.dropoff_date = s2.dropoff_date AND s1.regnum = s2.regnum
WHERE s2.regnum = 'CEZ 563'
GROUP BY e.empname, e.grade 
HAVING COUNT(w.[sid]) > 0
ORDER BY number_of_jobs DESC;
"""

result = cursor.execute(selectQuery)
resultList = []
for row in result:
    resultList.append(list(row))  # Convert each row to a list

tableColumns = ["Mechanic Name", "Mechanic Grade", "Number of Jobs"]
resultTable = pd.DataFrame(resultList, columns=tableColumns)
display(resultTable)
conn.close()

  Mechanic Name        Mechanic Grade  Number of Jobs
0    Tony Hoare  Apprentice                         1

In [20]:
conn = pyodbc.connect("Driver={SQL Server};Server=localhost\\SQLEXPRESS;Database=cw2;")
cursor = conn.cursor()

###############################
sql_query = """
DECLARE @start_date DATE = '2020-06-22';
DECLARE @end_date DATE = '2020-06-22';
SELECT emp.empid, emp.empname, 
       SUM(DATEDIFF(SECOND, '00:00:00', work.timespent)) / 60.0 AS total_minutes_spent
FROM work, emp
WHERE work.sid IN 
    (SELECT service.sid 
    FROM service 
    WHERE service.dropoff_date BETWEEN @start_date AND @end_date) 
AND work.empid IN (SELECT empid FROM emp)
GROUP BY emp.empid, emp.empname
ORDER BY total_minutes_spent DESC;
"""

result = cursor.execute(sql_query)
resultList = []
for row in result:
    resultList.append(list(row)) 
    
tableColumns = ["Employee ID", "Employee Name", "Total Minutes Spent"]
resultTable = pd.DataFrame(resultList, columns=tableColumns)
display(resultTable)
conn.close()

  Employee ID    Employee Name Total Minutes Spent
0       E0392  Edsger Dijkstra          565.000000
1       E1037    Edgar F. Codd          565.000000
2       E2045     Grace Hopper          565.000000
3       E2648      Alan Turing          565.000000
4       E4470     Ada Lovelace          565.000000
5       E7291       Tony Hoare          565.000000
6       E9274  Tim Berners-Lee          565.000000